### PR TITLE
Merge Upstream

### PR DESCRIPTION
**Pull request by josefbaltz**
Merge latest commits from Official EssentialsX repository

### CODE REVIEW

**Review by josefbaltz — COMMENTED** [review]
Nothing Conflicts with our current modifications

**Review by garrettsummerfi3ld — APPROVED** [review]
This looks good to merge, did a sanity check and it didn't do anything weird outside of new Essentials things.

We should probably target release builds rather than development builds as well as also get TeamCity to look at builds and test whether or not they will build with our changes and publish them here.

Approving for merge.

**Comment by josefbaltz** [comment]
> This looks good to merge, did a sanity check and it didn't do anything weird outside of new Essentials things.
> 
> 
> 
> We should probably target release builds rather than development builds as well as also get TeamCity to look at builds and test whether or not they will build with our changes and publish them here.
> 
> 
> 
> Approving for merge.

Let's go ahead and start targeting release builds. Do you want to get started on switching it over?

**Comment by garrettsummerfi3ld** [comment]
> > This looks good to merge, did a sanity check and it didn't do anything weird outside of new Essentials things.
> > 
> > 
> > 
> > We should probably target release builds rather than development builds as well as also get TeamCity to look at builds and test whether or not they will build with our changes and publish them here.
> > 
> > 
> > 
> > Approving for merge.
> 
> Let's go ahead and start targeting release builds. Do you want to get started on switching it over?

We can look into this, as messing with history and reverting commits only to add them back later is messy in Git, however if we were to only update from upstream once an official release is made, we can target those.

If we also want to roll release from upstream we could set TeamCity to check each commit made to upstream and verify if Essentials has a bad build or a bad commit and determine to merge from upstream.

**Pull request merged**
